/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { Public } from "../../decorators/public.decorator";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: {
        ...data,

        adoptionRequests: data.adoptionRequests
          ? {
              connect: data.adoptionRequests,
            }
          : undefined,

        lostAndFoundReports: data.lostAndFoundReports
          ? {
              connect: data.lostAndFoundReports,
            }
          : undefined,

        pets: data.pets
          ? {
              connect: data.pets,
            }
          : undefined,
      },
      select: {
        adoptionRequests: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        firstName: true,
        id: true,

        lostAndFoundReports: {
          select: {
            id: true,
          },
        },

        pets: {
          select: {
            id: true,
          },
        },

        phonenumber: true,
        profilePicture: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        adoptionRequests: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        firstName: true,
        id: true,

        lostAndFoundReports: {
          select: {
            id: true,
          },
        },

        pets: {
          select: {
            id: true,
          },
        },

        phonenumber: true,
        profilePicture: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        adoptionRequests: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        firstName: true,
        id: true,

        lostAndFoundReports: {
          select: {
            id: true,
          },
        },

        pets: {
          select: {
            id: true,
          },
        },

        phonenumber: true,
        profilePicture: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: {
          ...data,

          adoptionRequests: data.adoptionRequests
            ? {
                connect: data.adoptionRequests,
              }
            : undefined,

          lostAndFoundReports: data.lostAndFoundReports
            ? {
                connect: data.lostAndFoundReports,
              }
            : undefined,

          pets: data.pets
            ? {
                connect: data.pets,
              }
            : undefined,
        },
        select: {
          adoptionRequests: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          firstName: true,
          id: true,

          lostAndFoundReports: {
            select: {
              id: true,
            },
          },

          pets: {
            select: {
              id: true,
            },
          },

          phonenumber: true,
          profilePicture: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          adoptionRequests: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          firstName: true,
          id: true,

          lostAndFoundReports: {
            select: {
              id: true,
            },
          },

          pets: {
            select: {
              id: true,
            },
          },

          phonenumber: true,
          profilePicture: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
