/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdoptionRequestWhereUniqueInput } from "../../adoptionRequest/base/AdoptionRequestWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { LostAndFoundReportWhereUniqueInput } from "../../lostAndFoundReport/base/LostAndFoundReportWhereUniqueInput";
import { PetWhereUniqueInput } from "../../pet/base/PetWhereUniqueInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumUserRoles } from "./EnumUserRoles";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => AdoptionRequestWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdoptionRequestWhereUniqueInput)
  @IsOptional()
  @Field(() => AdoptionRequestWhereUniqueInput, {
    nullable: true,
  })
  adoptionRequests?: AdoptionRequestWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LostAndFoundReportWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => LostAndFoundReportWhereUniqueInput)
  @IsOptional()
  @Field(() => LostAndFoundReportWhereUniqueInput, {
    nullable: true,
  })
  lostAndFoundReports?: LostAndFoundReportWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => PetWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PetWhereUniqueInput)
  @IsOptional()
  @Field(() => PetWhereUniqueInput, {
    nullable: true,
  })
  pets?: PetWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phonenumber?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  profilePicture?: InputJsonValue;

  @ApiProperty({
    required: true,
    enum: EnumUserRoles,
  })
  @IsEnum(EnumUserRoles)
  @Field(() => EnumUserRoles)
  roles!: "User" | "Admin";

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
