/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdoptionRequest } from "../../adoptionRequest/base/AdoptionRequest";

import {
  ValidateNested,
  IsOptional,
  IsInt,
  Min,
  Max,
  IsString,
  MaxLength,
  IsDate,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { AiMatch } from "../../aiMatch/base/AiMatch";
import { EnumPetGender } from "./EnumPetGender";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";
import { User } from "../../user/base/User";
import { EnumPetStatus } from "./EnumPetStatus";
import { EnumPetTypeField } from "./EnumPetTypeField";

@ObjectType()
class Pet {
  @ApiProperty({
    required: false,
    type: () => [AdoptionRequest],
  })
  @ValidateNested()
  @Type(() => AdoptionRequest)
  @IsOptional()
  adoptionRequests?: Array<AdoptionRequest>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(1)
  @Max(30)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  age!: number | null;

  @ApiProperty({
    required: false,
    type: () => AiMatch,
  })
  @ValidateNested()
  @Type(() => AiMatch)
  @IsOptional()
  aiMatches?: AiMatch | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(100)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  breed!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumPetGender,
  })
  @IsEnum(EnumPetGender)
  @IsOptional()
  @Field(() => EnumPetGender, {
    nullable: true,
  })
  gender?: "Male" | "Female" | "Unknown" | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  imageUrl!: JsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  owner?: User | null;

  @ApiProperty({
    required: false,
    enum: EnumPetStatus,
  })
  @IsEnum(EnumPetStatus)
  @IsOptional()
  @Field(() => EnumPetStatus, {
    nullable: true,
  })
  status?: "Available" | "Adopted" | "Lost" | "Found" | null;

  @ApiProperty({
    required: false,
    enum: EnumPetTypeField,
  })
  @IsEnum(EnumPetTypeField)
  @IsOptional()
  @Field(() => EnumPetTypeField, {
    nullable: true,
  })
  typeField?: "Cat" | "Dog" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Pet as Pet };
