// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzmsmkkbelbuvgmfucsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6bXNta2tiZWxidXZnbWZ1Y3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODEyNjksImV4cCI6MjA2MTk1NzI2OX0.HUKD6758rO49JLthZvak9fix_sl2cBYbsgsWzHZge1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);