/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AiMatchWhereUniqueInput } from "../../aiMatch/base/AiMatchWhereUniqueInput";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { EnumLostAndFoundReportPetType } from "./EnumLostAndFoundReportPetType";
import { EnumLostAndFoundReportReportType } from "./EnumLostAndFoundReportReportType";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class LostAndFoundReportWhereInput {
  @ApiProperty({
    required: false,
    type: () => AiMatchWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AiMatchWhereUniqueInput)
  @IsOptional()
  @Field(() => AiMatchWhereUniqueInput, {
    nullable: true,
  })
  aiMatches?: AiMatchWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  contactInfo?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  imageUrl?: JsonFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  location?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  petName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumLostAndFoundReportPetType,
  })
  @IsEnum(EnumLostAndFoundReportPetType)
  @IsOptional()
  @Field(() => EnumLostAndFoundReportPetType, {
    nullable: true,
  })
  petType?: "Dog" | "Cat";

  @ApiProperty({
    required: false,
    enum: EnumLostAndFoundReportReportType,
  })
  @IsEnum(EnumLostAndFoundReportReportType)
  @IsOptional()
  @Field(() => EnumLostAndFoundReportReportType, {
    nullable: true,
  })
  reportType?: "Lost" | "Found";

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  reportedBy?: UserWhereUniqueInput;
}

export { LostAndFoundReportWhereInput as LostAndFoundReportWhereInput };
