/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AiMatchWhereUniqueInput } from "../../aiMatch/base/AiMatchWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumLostAndFoundReportPetType } from "./EnumLostAndFoundReportPetType";
import { EnumLostAndFoundReportReportType } from "./EnumLostAndFoundReportReportType";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class LostAndFoundReportCreateInput {
  @ApiProperty({
    required: false,
    type: () => AiMatchWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AiMatchWhereUniqueInput)
  @IsOptional()
  @Field(() => AiMatchWhereUniqueInput, {
    nullable: true,
  })
  aiMatches?: AiMatchWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactInfo?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  imageUrl?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  petName?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumLostAndFoundReportPetType,
  })
  @IsEnum(EnumLostAndFoundReportPetType)
  @IsOptional()
  @Field(() => EnumLostAndFoundReportPetType, {
    nullable: true,
  })
  petType?: "Dog" | "Cat" | null;

  @ApiProperty({
    required: false,
    enum: EnumLostAndFoundReportReportType,
  })
  @IsEnum(EnumLostAndFoundReportReportType)
  @IsOptional()
  @Field(() => EnumLostAndFoundReportReportType, {
    nullable: true,
  })
  reportType?: "Lost" | "Found" | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  reportedBy?: UserWhereUniqueInput | null;
}

export { LostAndFoundReportCreateInput as LostAndFoundReportCreateInput };
